ACETutoring/ACETutoring/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

# make the frontpage app handle all the requirements on first entering the site  
urlpatterns = [
    path('',include('frontpage.urls')),
    path('blog/',include('blog.urls')),
    path('new/',include('studentrequest.urls')),
    path('store/',include('store.urls')),
    path('admin/', admin.site.urls), 
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) # warning don't use last concat in production

ACETutoring/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    #path('',views.blog,name='blog'),
    path('<int:pk>/',views.blog,name='fullblog'),
]

ACETutoring/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('',views.books,name='bookindex'),
    path('<int:pk>/',views.bookdetail,name='bookdetail'),
    path('add/<int:revisionbook_id>/cart',views.add_to_cart,name='add_to_cart'),
    path('remove/<int:item_id>/cart',views.remove_from_cart,name='remove_from_cart'),
    path('store/', views.view_cart, name='view_cart'),
    path('check_out/', views.check_out, name='check_out'),
]

ACETutoring/store/models.py
from django.db import models
from studentrequest.models import Subject
from django.contrib.auth.models import User

# Create your models here.

# this class has the fields of the books sold on the site
class RevisionBook(models.Model):
    title = models.CharField(max_length=255)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    price = models.FloatField()
    image = models.ImageField(upload_to='store_images')
    description = models.CharField(max_length=2000)

    def __str__(self):
        return self.title
    

    
# a data model for the current cart of the user 
class CartItem(models.Model):
    product = models.ForeignKey(RevisionBook,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return f'{self.quantity} x {self.product.name}'
    

ACETutoring/store/forms.py
from django import forms

from .models import RevisionBook

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

# the form for the creating new revision books for sale
class NewRevisionBookForm(forms.ModelForm):
    class Meta:
        model = RevisionBook
        fields = ('subject', 'title','price','image','description')
        widgets = {
            'subject': forms.Select(attrs = {
            'class': INPUT_CLASSES
            }),
            'title': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            })

    }

ACETutoring/store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import RevisionBook, CartItem
from studentrequest.models import Subject

"""This function creates the view for the store index page; right now it is kept basic as it is not final which filter/query features 
will make it to the final version"""

def books(request):
    """
     query = request.GET.get('query','')
    """

    """
    subject_id = request.GET.get('subject_id',0)
    """
    subjects = Subject.objects.all()
    books = RevisionBook.objects.all()
    """
    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    """
    
    return render(request, 'store/bookindex.html',{
        'revisionbooks': books,
        #'query': query,
        'subject' : subjects,
        #'category_id': int(category_id)
    })

def bookdetail(request, pk):
    item = get_object_or_404(RevisionBook, pk=pk)
    related_items = RevisionBook.objects.filter(subject=item.subject).exclude(pk=pk)[0:3]
    return render(request, 'store/bookdetail.html', {
        'revisionbook': item,
        'related_revisionbooks': related_items
    })

def add_to_cart(request, revisionbook_id):
    product = RevisionBook.objects.get(id=revisionbook_id)
    cart_item, created = CartItem.objects.get_or_create(product=product, user=request.user)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('store:view_cart')


def book_list(request):
    revisionbook = RevisionBook.objects.all()
    return render(request, 'frontpage/bookindex.html', {'revisionbook': revisionbook})
 
def view_cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    total_price = round(sum(item.product.price * item.quantity for item in cart_items),2)
    return render(request, 'store/cart.html', {'cart_items': cart_items, 'total_price': total_price, 'checkout': False})
  
def remove_from_cart(request, item_id):
    cart_item = CartItem.objects.get(id=item_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('store:view_cart')

# due to the scope of the project, I will not be handling payment so this just resets the queue 
def check_out(request):
    cart_items = CartItem.objects.filter(user=request.user)
    for item in cart_items:
        item.quantity = 0
        item.delete()
    return render(request, 'store/cart.html', {'checkout':True})

ACETutoring/store/templates/store/bookdetail.html
{% extends 'frontpage/frontpage.html' %}

{% block title%}{{ revisionbook.title }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
  <div class="colspan-3">
    <img src = "{{ revisionbook.image.url }}" class = "rounded-xl">
    </div>

  <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{ revisionbook.title }}</h1>
    <p class="text-gray-500"><strong>Price: </strong>{{ revisionbook.price }}</p>
    {% if revisionbook.description %}
       <p class="text-gray-700">
           <strong class="text-gray-500">Description:</strong><br>
           {{ revisionbook.description }}
       </p>
    {% endif %}

    <a href="{% url 'store:add_to_cart' revisionbook.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 rounded-xl text-white hover:bg-teal-700">Add to cart</a>


  </div>
</div>
<div class="mt-6 px py-12 bg-gray-100 rounded-x1">
        <h2 class="mb-12 text-2xl text-center">Related material </h2>
        <div class="grid grid-cols-3 gap-3">
           {% for revisionbook in related_revisionbooks %}
            <div>
                <a href="{% url 'store:bookdetail' revisionbook.id %}">
                    <div>
                        <img src="{{ revisionbook.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ revisionbook.title }}</h2>
                        <p class="text-gray-500">Price: {{ revisionbook.price }} </p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

ACETutoring/store/templates/store/bookindex.html
{% extends 'frontpage/frontpage.html' %}
{% block title %}Revision Books{% endblock %}
{% block content %}
<style>
    .image-container {
        height: 200px;
        /*hide overflow to prevent the lower part of the image being seen where the text description should be seen*/  
        overflow: hidden; 
    }

    .image-container img {
        width: 100%;  
        height: 100%; 
        /*maintain aspect-ratio*/
        object-fit: cover;  
    }
</style>

   <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100 grid">
      <div class="col-span-1">
        <a href="{% url 'store:view_cart' %}" class="px-6 py-2 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">View Cart</a>
      </div>
       <div class="col-span-3">
           <div class="grid grid-cols-3 gap-3">
           {% for revisionbook in revisionbooks %}
            <div>
                <a href="{% url 'store:bookdetail' revisionbook.id %}">
                    <div class="image-container">
                        <img src="{{ revisionbook.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ revisionbook.title }}</h2>
                        <p class="text-gray-500">Price: {{ revisionbook.price }} </p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
       </div>
   </div>
{% endblock %}

ACETutoring/store/templates/store/cart.html
{% extends 'frontpage/frontpage.html' %}
{% block title %}Revision Books{% endblock %}
{% block content %} 
<body>
    {% if checkout == True %}
    <h1 class="text-lg text-gray-500 my-3">Thank you for your purchase</h1>
    <a href="{% url 'store:bookindex' %}" class="px-6 py-2 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Continue Shopping</a>
    {% else %}
    <h1 class="text-lg text-gray-500">Your Shopping Cart</h1>
 
    <div class="product-list">
 
    {% for item in cart_items %}
    <div class="my-2 col-span-2 p-4 bg-gray-100 rounded-xl">
        <div class="product-item">
            <p class="my-3 text-lg text-gray-500">{{ item.product.title }} ({{ item.quantity }})</p>
            <p class="my-3 text-lg text-gray-500">Price: ${{ item.product.price }}</p>
            <a href="{% url 'store:remove_from_cart' item.id %}" class="px-6 py-2 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Remove</a>
        </div>
    </div>
    {% empty %}
    <div class="my-2 col-span-2 p-4 bg-gray-100 rounded-xl">
        <p class="text-lg text-gray-500">Your cart is empty.</p>
    </div>
    {% endfor %}
 
    </div>
 
    <p class="my-3 text-lg text-gray-500">Total Price: ${{ total_price }}</p>
 
    <a href="{% url 'store:bookindex' %}" class="px-6 py-2 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Continue Shopping</a>
    <a href="{% url 'store:check_out' %}" class="px-6 py-2 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Check Out</a>
    {% endif %}
</body>
 
{% endblock %}