ACETutoring/ACETutoring/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

# make the frontpage app handle all the requirements on first entering the site  
urlpatterns = [
    path('',include('frontpage.urls')),
    path('blog/',include('blog.urls')),
    path('new/',include('studentrequest.urls')),
    path('store/',include('store.urls')),
    path('admin/', admin.site.urls), 
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) # warning don't use last concat in production

ACETutoring/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    #path('',views.blog,name='blog'),
    path('<int:pk>/',views.blog,name='fullblog'),
]

ACETutoring/frontpage/urls.py
from django.urls import path
from . import views 


"""contains url patterns for the front page"""

app_name = 'frontpage'

urlpatterns = [
    path('', views.index_blogs,name='blogindex'),
]

ACETutoring/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('',views.books,name='bookindex'),
    path('<int:pk>/',views.bookdetail,name='bookdetail'),
    path('add/<int:revisionbook_id>/cart',views.add_to_cart,name='add_to_cart'),
    path('remove/<int:item_id>/cart',views.remove_from_cart,name='remove_from_cart'),
    path('store/', views.view_cart, name='view_cart'),
    path('check_out/', views.check_out, name='check_out'),
]

ACETutoring/studentrequest/urls.py
from django.urls import path
from . import views

app_name = 'studentrequest'

urlpatterns = [
    path('',views.new,name='new')
]

ACETutoring/frontpage/models.py
from django.db import models

# Create your models here.

ACETutoring/frontpage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Blog, Subject

# Create your views here.

# this view renders the front page 
def frontpage(request):
    return render(request,'frontpage/frontpage.html')

def index_blogs(request):
    blogs = Blog.objects.filter()[0:6]

    return render(request,'frontpage/blogindex.html',{
        'blogs' : blogs
    })

ACETutoring/frontpage/templates/frontpage/blogindex.html
{% extends 'frontpage/frontpage.html'%}
{% block tile %}Latest Blogs from ACE Tutoring{%endblock%}
{% block content %}

    <div class="mt-6 px py-12 bg-gray-100 rounded-x1">
        <h2 class="mb-12 text-2xl text-center">Blogs</h2>

        <div class="grid grid-cols-3 gap-3">
           {% for blog in blogs %}
            <div> 
                <a href="{% url 'blog:fullblog' blog.id %}">
                    <div class="p-6 bg-white rounded-b-4xl">
                            <p class = "bg-{{ blog.subject.backgroundColor }}-50">{{ blog.subject }}</p>
                        <div>
                            <img src="{{ blog.image.url }}" class="rounded-t-xl">
                        </div>
                        <h2 class="text-2xl">{{ blog.title }}</h2>
                        <p class="text-gray-500">Date of publication: {{ blog.date }} </p>
                        <p class="text-gray-500">Author: {{ blog.author }} </p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

ACETutoring/frontpage/templates/frontpage/frontpage.html
<!doctype html>
<html>
     <head>
         <meta charset="utf-8">
         <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <script src="https://cdn.tailwindcss.com"></script>

         <title>{%block title%}{% endblock %} | ACE Tutoring</title>
     </head>

     <body>
         <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">

             <a href="/" class="text-xl font-semibold">
                {% if request.path != '/' %} Home {% else %} ACE Tutoring {% endif %}</a>
             <div class="space-x-6">
                 <a href="{% url 'studentrequest:new' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up for a session</a>
                 <a href="{% url 'store:bookindex' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Browse revision content</a>
             </div>
         </nav>

         <div class="px-6 py-6">
             {% block content %}
             {% endblock %}
         </div>
         <footer  class="py-6 px-6 flex justify-between bg-gray-800">
             <div class="w=-2/3 pr-10">
                 <h3 class="mb-5 font-semibold text-gray-400">About</h3>
             </div>

             <div class="w-1/3">
                 <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

             </div>>
             <h4 class="mb-5 font-semibold text-gray-400">credit: www.geonames.org</h4>
         </footer>
     </body>
</html>